### PR TITLE
Added pem needed for windows ruby_install.

### PR DESCRIPTION
**Pull request by tylercloke**

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by schisamo** [comment]
@tylercloke I bumped the metadata version so `verify/syntax` passed.

**Comment by elliott-davis** [comment]
:+1: LGTM

**Comment by elliott-davis** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Change: 4b2c8288-ed56-4345-98f0-564ec79de70a approved by: @elliott-davis

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Comment by schisamo** [comment]
@delivery deliver

**Comment by chef-delivery** [comment]
Change: 4b2c8288-ed56-4345-98f0-564ec79de70a delivered by: @schisamo

**Pull request merged**
