### PR TITLE
Begin linting with CookStyle

### PR DESCRIPTION
**Pull request by schisamo**
/cc @chef-cookbooks/engineering-services

### CODE REVIEW

**Comment by scotthain** [comment]
👍

**Comment by sersut** [comment]
👍 if Travis is happy.

**Comment by yzl** [comment]
👍  pending travis being happy

**Comment by rhass** [comment]
I am cherry-picking these changes into #37 and I was able to reproduce the travis failure locally. I believe have identified and fixed the issue which was causing travis to fail in this PR, so let's hope travis agrees with my local test results. :smile:

**Pull request closed without merging**
