### PR TITLE
Updated Node install to use /usr/local/bin/nvm as install path

### PR DESCRIPTION
**Pull request by elliott-davis**
Ping: @chef-cookbooks/delivery-migration-team @schisamo

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by elliott-davis** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Change: dc353d7b-29fc-43a1-8eff-34fc79ade0f2 approved by: @elliott-davis

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Pull request merged**
