### PR TITLE
A few Delivery build cookbook fixes

### PR DESCRIPTION
**Pull request by schisamo**
/cc @chef-cookbooks/delivery-migration-team

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by elliott-davis** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Change: 4129e939-f5a3-49ce-94b2-2c934787fed2 approved by: @elliott-davis

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Comment by schisamo** [comment]
@delivery deliver

**Comment by chef-delivery** [comment]
Change: 4129e939-f5a3-49ce-94b2-2c934787fed2 delivered by: @schisamo

**Pull request merged**
