### PR TITLE
Go support

### PR DESCRIPTION
**Pull request by srenatus**
Hi there.

This should add Go to these fine languages. I've got to admit that I haven't run the tests on all platforms (only recent-ish Linux distributions).

Cheers! :smiley:

### CODE REVIEW

**Comment by oferrigni** [comment]
Thank you for the contribution!! A lot of people are on holiday. This might not get reviewed till after the new year. Is that alright or do you need faster turnaround?

**Comment by srenatus** [comment]
Totally fine with me. Happy holidays :)

**Comment by rhass** [comment]
The travis issues have been resolved. If you don't mind, could you rebase off master to pull in the fixes? Thanks!

**Comment by tas50** [comment]
@srenatus If you care to rebase this I'll get it merged in

**Comment by srenatus** [comment]
@tas50 I think rebasing isn't nearly enough, though... I'd be surprised if what worked for 1.5.2 still works for 1.10 🤔

**Comment by tas50** [comment]
Closing this out then. Thanks for the response.

**Pull request closed without merging**
