### PR TITLE
Add Apache 2.0 license file.

### PR DESCRIPTION
**Pull request by yzl**

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by oferrigni** [comment]
:+1:

**Comment by oferrigni** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Change: bf02a80e-5d69-424b-a0cb-87e655bada86 approved by: @oferrigni

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Comment by yzl** [comment]
@delivery deliver

**Comment by chef-delivery** [comment]
Change: bf02a80e-5d69-424b-a0cb-87e655bada86 delivered by: @yzl

**Pull request merged**
