### PR TITLE
Fixed directory copy failure

### PR DESCRIPTION
**Pull request by elliott-davis**
Entire NVM directory was being copied for some versions of node that were pathed differently

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by schisamo** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Change: e83114c4-c315-46e8-94c0-7fab8095feb4 approved by: @schisamo

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Comment by schisamo** [comment]
@delivery deliver

**Comment by chef-delivery** [comment]
Change: e83114c4-c315-46e8-94c0-7fab8095feb4 delivered by: @schisamo

**Pull request merged**
