### PR TITLE
Refactor/Cleanup for `ruby_execute`

### PR DESCRIPTION
**Pull request by schisamo**
/cc @chef-cookbooks/delivery-migration-team

### CODE REVIEW

**Comment by tylercloke** [comment]
:+1: Let's get this merged so I can continue making my changes on it.

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by schisamo** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Change: cfb7446c-6cc1-4bbb-92d7-2daf181dafa8 approved by: @schisamo

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Comment by schisamo** [comment]
@delivery deliver

**Comment by chef-delivery** [comment]
Change: cfb7446c-6cc1-4bbb-92d7-2daf181dafa8 delivered by: @schisamo

**Pull request merged**
